name: linting

on:
  workflow_dispatch:
  pull_request:

jobs:
  black:
    name: run black linter
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: lint with black
        uses: rickstaa/action-black@v1
        with:
          black_args: "src --check"
